### ISSUE TITLE
enable  python logger package by default when compiling 

### ISSUE THREAD

**Issue by shah0237** [CheckPointSW/harmony-endpoint-management-py-sdk#12]
optional feature request,

Users sometimes having issue creating env variables, feel free to ignore request if rational to have it off by default is justified.

**Comment by chkp-haimk** [comment]
Hi @shah0237 

Thank you for your comment.

There is a way to turn on the logger programmatically.

See https://github.com/CheckPointSW/harmony-endpoint-management-py-sdk/blob/669dcb64e493ef172f1dc8e0e7735c9471c0fcc0/README.md?plain=1#L179-L184

You don't have to use env variables to use the logger.

We do not want to open it by default since it's an SDK library meant to be part of other systems.

Feel free to re-open the issue if you have a suggestion for another way to enable it.
